services:
  telegram-bot:
    build: .
    ports:
      - 5000:80
    env_file:
      - .env
    volumes:
      - ./telegram_bot:/app

  redis:
    image: redis:7.2-rc
    volumes:
      - redis:/data

volumes:
  redis:
